(function($) {

	'use strict';

	window.requestAnimFrame = (function(){
		return window.requestAnimationFrame ||
		window.webkitRequestAnimationFrame ||
		window.mozRequestAnimationFrame ||
		function( callback ){
			window.setTimeout(callback, 1000 / 60);
		};
	})();

	$(document).ready(function() {

		/*===========================
		=            WOW            =
		===========================*/
		new WOW().init();

		/*=================================
		=            Particles            =
		=================================*/

		var $headerSizer, width, height, canvas, ctx, circles, animateHeader = true;

		if ($('#intro .bg').length > 0) {
			$headerSizer = $('#intro .bg');
		} else {
			$headerSizer = $('#intro');
		}

		initHeader();
		addListeners();

		function initHeader() {
			width = $headerSizer.width();
			height = $headerSizer.height();

			canvas = document.getElementById('particles');
			canvas.width = width;
			canvas.height = height;
			ctx = canvas.getContext('2d');

			circles = [];
			for(var x = 0; x < width * 0.3; x++) {
				var c = new Circle();
				circles.push(c);
			}
			animate();
		}

		function addListeners() {
			window.addEventListener('scroll', scrollCheck);
			window.addEventListener('resize', resize);
		}

		function scrollCheck() {
			if (document.body.scrollTop > height) {
				animateHeader = false;
			} else {
				animateHeader = true;
			}
		}

		function resize() {
			width = $headerSizer.width();
			height = $headerSizer.height();
			canvas.width = width;
			canvas.height = height;
		}

		function animate() {
			if(animateHeader) {
				ctx.clearRect(0, 0, width, height);
				for(var i in circles) {
					circles[i].draw();
				}
			}
			requestAnimationFrame(animate);
		}

		function Circle() {
			var self = this;

			(function() {
				self.pos = {};
				init();
			})();

			function init() {
				self.pos.x = Math.random() * width;
				self.pos.y = height + Math.random() * 100;
				self.alpha = 0.1 + Math.random() * 0.3;
				self.scale = 0.1 + Math.random() * 0.3;
				self.velocity = Math.random();
			}

			this.draw = function() {
				if(self.alpha <= 0) {
					init();
				}
				self.pos.x += self.velocity;
				self.pos.y -= self.velocity;
				self.alpha -= 0.0005;
				ctx.beginPath();
				ctx.arc(self.pos.x, self.pos.y, self.scale * 10, 0, 2 * Math.PI, false);
				ctx.fillStyle = 'rgba(255,255,255,' + self.alpha + ')';
				ctx.fill();
			};
		}

		// Generated by CoffeeScript 1.9.3
(function(){var e;e=function(){function e(e,t){var n,r;this.options={target:"instafeed",get:"popular",resolution:"thumbnail",sortBy:"none",links:!0,mock:!1,useHttp:!1};if(typeof e=="object")for(n in e)r=e[n],this.options[n]=r;this.context=t!=null?t:this,this.unique=this._genKey()}return e.prototype.hasNext=function(){return typeof this.context.nextUrl=="string"&&this.context.nextUrl.length>0},e.prototype.next=function(){return this.hasNext()?this.run(this.context.nextUrl):!1},e.prototype.run=function(t){var n,r,i;if(typeof this.options.clientId!="string"&&typeof this.options.accessToken!="string")throw new Error("Missing clientId or accessToken.");if(typeof this.options.accessToken!="string"&&typeof this.options.clientId!="string")throw new Error("Missing clientId or accessToken.");return this.options.before!=null&&typeof this.options.before=="function"&&this.options.before.call(this),typeof document!="undefined"&&document!==null&&(i=document.createElement("script"),i.id="instafeed-fetcher",i.src=t||this._buildUrl(),n=document.getElementsByTagName("head"),n[0].appendChild(i),r="instafeedCache"+this.unique,window[r]=new e(this.options,this),window[r].unique=this.unique),!0},e.prototype.parse=function(e){var t,n,r,i,s,o,u,a,f,l,c,h,p,d,v,m,g,y,b,w,E,S,x,T,N,C,k,L,A,O,M,_,D;if(typeof e!="object"){if(this.options.error!=null&&typeof this.options.error=="function")return this.options.error.call(this,"Invalid JSON data"),!1;throw new Error("Invalid JSON response")}if(e.meta.code!==200){if(this.options.error!=null&&typeof this.options.error=="function")return this.options.error.call(this,e.meta.error_message),!1;throw new Error("Error from Instagram: "+e.meta.error_message)}if(e.data.length===0){if(this.options.error!=null&&typeof this.options.error=="function")return this.options.error.call(this,"No images were returned from Instagram"),!1;throw new Error("No images were returned from Instagram")}this.options.success!=null&&typeof this.options.success=="function"&&this.options.success.call(this,e),this.context.nextUrl="",e.pagination!=null&&(this.context.nextUrl=e.pagination.next_url);if(this.options.sortBy!=="none"){this.options.sortBy==="random"?M=["","random"]:M=this.options.sortBy.split("-"),O=M[0]==="least"?!0:!1;switch(M[1]){case"random":e.data.sort(function(){return.5-Math.random()});break;case"recent":e.data=this._sortBy(e.data,"created_time",O);break;case"liked":e.data=this._sortBy(e.data,"likes.count",O);break;case"commented":e.data=this._sortBy(e.data,"comments.count",O);break;default:throw new Error("Invalid option for sortBy: '"+this.options.sortBy+"'.")}}if(typeof document!="undefined"&&document!==null&&this.options.mock===!1){m=e.data,A=parseInt(this.options.limit,10),this.options.limit!=null&&m.length>A&&(m=m.slice(0,A)),u=document.createDocumentFragment(),this.options.filter!=null&&typeof this.options.filter=="function"&&(m=this._filter(m,this.options.filter));if(this.options.template!=null&&typeof this.options.template=="string"){f="",d="",w="",D=document.createElement("div");for(c=0,N=m.length;c<N;c++){h=m[c],p=h.images[this.options.resolution];if(typeof p!="object")throw o="No image found for resolution: "+this.options.resolution+".",new Error(o);E=p.width,y=p.height,b="square",E>y&&(b="landscape"),E<y&&(b="portrait"),v=p.url,l=window.location.protocol.indexOf("http")>=0,l&&!this.options.useHttp&&(v=v.replace(/https?:\/\//,"//")),d=this._makeTemplate(this.options.template,{model:h,id:h.id,link:h.link,type:h.type,image:v,width:E,height:y,orientation:b,caption:this._getObjectProperty(h,"caption.text"),likes:h.likes.count,comments:h.comments.count,location:this._getObjectProperty(h,"location.name")}),f+=d}D.innerHTML=f,i=[],r=0,n=D.childNodes.length;while(r<n)i.push(D.childNodes[r]),r+=1;for(x=0,C=i.length;x<C;x++)L=i[x],u.appendChild(L)}else for(T=0,k=m.length;T<k;T++){h=m[T],g=document.createElement("img"),p=h.images[this.options.resolution];if(typeof p!="object")throw o="No image found for resolution: "+this.options.resolution+".",new Error(o);v=p.url,l=window.location.protocol.indexOf("http")>=0,l&&!this.options.useHttp&&(v=v.replace(/https?:\/\//,"//")),g.src=v,this.options.links===!0?(t=document.createElement("a"),t.href=h.link,t.appendChild(g),u.appendChild(t)):u.appendChild(g)}_=this.options.target,typeof _=="string"&&(_=document.getElementById(_));if(_==null)throw o='No element with id="'+this.options.target+'" on page.',new Error(o);_.appendChild(u),a=document.getElementsByTagName("head")[0],a.removeChild(document.getElementById("instafeed-fetcher")),S="instafeedCache"+this.unique,window[S]=void 0;try{delete window[S]}catch(P){s=P}}return this.options.after!=null&&typeof this.options.after=="function"&&this.options.after.call(this),!0},e.prototype._buildUrl=function(){var e,t,n;e="https://api.instagram.com/v1";switch(this.options.get){case"popular":t="media/popular";break;case"tagged":if(!this.options.tagName)throw new Error("No tag name specified. Use the 'tagName' option.");t="tags/"+this.options.tagName+"/media/recent";break;case"location":if(!this.options.locationId)throw new Error("No location specified. Use the 'locationId' option.");t="locations/"+this.options.locationId+"/media/recent";break;case"user":if(!this.options.userId)throw new Error("No user specified. Use the 'userId' option.");t="users/"+this.options.userId+"/media/recent";break;default:throw new Error("Invalid option for get: '"+this.options.get+"'.")}return n=e+"/"+t,this.options.accessToken!=null?n+="?access_token="+this.options.accessToken:n+="?client_id="+this.options.clientId,this.options.limit!=null&&(n+="&count="+this.options.limit),n+="&callback=instafeedCache"+this.unique+".parse",n},e.prototype._genKey=function(){var e;return e=function(){return((1+Math.random())*65536|0).toString(16).substring(1)},""+e()+e()+e()+e()},e.prototype._makeTemplate=function(e,t){var n,r,i,s,o;r=/(?:\{{2})([\w\[\]\.]+)(?:\}{2})/,n=e;while(r.test(n))s=n.match(r)[1],o=(i=this._getObjectProperty(t,s))!=null?i:"",n=n.replace(r,""+o);return n},e.prototype._getObjectProperty=function(e,t){var n,r;t=t.replace(/\[(\w+)\]/g,".$1"),r=t.split(".");while(r.length){n=r.shift();if(!(e!=null&&n in e))return null;e=e[n]}return e},e.prototype._sortBy=function(e,t,n){var r;return r=function(e,r){var i,s;return i=this._getObjectProperty(e,t),s=this._getObjectProperty(r,t),n?i>s?1:-1:i<s?1:-1},e.sort(r.bind(this)),e},e.prototype._filter=function(e,t){var n,r,i,s,o;n=[],r=function(e){if(t(e))return n.push(e)};for(i=0,o=e.length;i<o;i++)s=e[i],r(s);return n},e}(),function(e,t){return typeof define=="function"&&define.amd?define([],t):typeof module=="object"&&module.exports?module.exports=t():e.Instafeed=t()}(this,function(){return e})}).call(this);
		/*========================================
		=            Animated Letters            =
		========================================*/
		var animationDelay = 3000,
			lettersDelay = 100;

		function singleLetters($words) {
			$words.each(function(){
				var word = $(this),
				letters = word.text().split(''),
				selected = word.hasClass('is-visible');
				for (var i in letters) {
					letters[i] = '<em>' + letters[i] + '</em>';
					letters[i] = (selected) ? '<i class="in">' + letters[i] + '</i>' : '<i>' + letters[i] + '</i>';
				}
				var newLetters = letters.join('');
				word.html(newLetters).css('opacity', 1);
			});
		}

		function takeNext($word) {
			return (!$word.is(':last-child')) ? $word.next() : $word.parent().children().eq(0);
		}

		function switchWord($oldWord, $newWord) {
			$oldWord.removeClass('is-visible').addClass('is-hidden');
			$newWord.removeClass('is-hidden').addClass('is-visible');
		}

		function hideLetter($letter, $word, $bool, $duration) {
			$letter.removeClass('in').addClass('out');
			if(!$letter.is(':last-child')) {
				setTimeout(function(){ hideLetter($letter.next(), $word, $bool, $duration); }, $duration);
			} else if($bool) {
				setTimeout(function(){ hideWord(takeNext($word)); }, animationDelay);
			}
			if($letter.is(':last-child') && $('html').hasClass('no-csstransitions')) {
				var nextWord = takeNext($word);
				switchWord($word, nextWord);
			}
		}

		function showLetter($letter, $word, $bool, $duration) {
			$letter.addClass('in').removeClass('out');
			if(!$letter.is(':last-child')) {
				setTimeout(function(){ showLetter($letter.next(), $word, $bool, $duration); }, $duration);
			} else {
				if(!$bool) { setTimeout(function(){ hideWord($word); }, animationDelay); }
			}
		}

		function hideWord($word) {
			var nextWord = takeNext($word);
			var bool = ($word.children('i').length >= nextWord.children('i').length) ? true : false;
			hideLetter($word.find('i').eq(0), $word, bool, lettersDelay);
			showLetter(nextWord.find('i').eq(0), nextWord, bool, lettersDelay);
		}

		function animateHeadline($headlines) {
			var duration = animationDelay;
			$headlines.each(function(){
				var headline = $(this);
				setTimeout(function(){ hideWord( headline.find('.is-visible').eq(0) ); }, duration);
			});
		}

		function initHeadline() {
			singleLetters($('.animated-letters').find('b'));
			animateHeadline($('.animated-letters'));
		}

		initHeadline();

		/*===========================
		=            Nav            =
		===========================*/
		$('.btn-nav').click(function() {
			$('.main-nav').toggleClass('main-nav--visible');
		});

		$('.main-nav nav').onePageNav({
			easing: 'swing',
			scrollSpeed: 500,
			filter: ':not(.external)'
		});

		/*=====================================
		=            Button scroll            =
		=====================================*/
		$(document).on('click', '.btn-go', function(e) {
			e.preventDefault();
			var target = $(this).attr('href');
			var targetOffset = $(target).offset();
			$('html,body').animate({scrollTop: (targetOffset.top)}, 500);
		});

		/*==============================
		=            Skills            =
		==============================*/
		$('.skills .skills-item').each(function() {
			var progress = $(this).data('progress');
			$(this).css('width', progress + '%');
		});

		/*=================================
		=            Portfolio            =
		=================================*/
		$('.works').shuffle({
			itemSelector: '.works-item',
			gutterWidth: 30
		});

		$('.filter li').on('click', function() {
			var $this = $(this),
			isActive = $this.hasClass( 'active' ),
			group = isActive ? 'all' : $this.data('group');
			if ( !isActive ) {
				$('.filter .active').removeClass('active');
			}
			$this.toggleClass('active');
			$('.works').shuffle( 'shuffle', group );
		});

		$('.filtered .works-item-link').magnificPopup({
			type: 'inline',
			gallery: {
				enabled: true
			},
			mainClass: 'unica',
			removalDelay: 300
		});

		/*=================================
		=            Slideshow            =
		=================================*/
		$('.slideshow').owlCarousel({
			singleItem: true,
			autoPlay: true,
			theme: 'owl-unica',
			transitionStyle: 'UnicaAnim',
			navigationText: ['', '']
		});

		$('.clients').owlCarousel({
			items: 5,
			autoPlay: true,
			theme: 'owl-unica',
			pagination: false
		});

		/*=======================================
		=            Form validation            =
		=======================================*/
		$('.contact-form').validate({
			errorClass: 'input--error',
			validClass: 'input--success',
			errorPlacement: function() {
				return true;
			},
			highlight: function(element, errorClass) {
				$(element).parents('.input').addClass(errorClass);
			},
			unhighlight: function(element, errorClass) {
				$(element).parents('.input').removeClass(errorClass);
			},
			rules: {
				email: {
					email: true
				}
			}
		});

		/*===================================
		=            Form submit            =
		===================================*/
		$('.contact-form').submit(function(e){
			e.preventDefault();
			var $form = $(this),
				$submit = $form.find('input[type="submit"]');
			if( $form.valid() ){
				var dataString = $form.serialize();
				$submit.before('<div class="loader"></div>');
				$.ajax({
					type: $form.attr('method'),
					url: $form.attr('action'),
					data: dataString,
					success: function() {
						$submit.before('<div class="message message-success">Your message was sent successfully!</div>');
					},
					error: function() {
						$submit.before('<div class="message message-error">Your message wasn\'t sent, please try again.</div>');
					},
					complete: function() {
						$form.find('.loader').remove();
						$form.find('.message').fadeIn();
						setTimeout(function() {
							$form.find('.message').fadeOut(function() {
								$(this).remove();
							});
						}, 5000);
					}
				});
			}
		});

		/*==============================
		=            Inputs            =
		==============================*/
		$('.input-field-item').each( function() {
			var $parentEl = $(this).parents('.input');
			if( $(this).val() !== '' ) {
				$.trim($(this).val());
				$parentEl.addClass('input--filled');
			}
			$(this).on('focus', function() {
				$parentEl.addClass('input--focused input--filled');
			});
			$(this).on('blur', function() {
				$parentEl.removeClass('input--focused');
				if( $.trim($(this).val()) === '' ) {
					$parentEl.removeClass('input--filled');
				}
			});
		});

		/*==============================
		=            Tweets            =
		==============================*/
		var tweetsID = 'tweets',
		tweetsEl = document.getElementById(tweetsID);
		if (tweetsEl) {
			var tweetsConfig = {
				'id': tweetsEl.getAttribute('data-id'),
				'domId': tweetsID,
				'maxTweets': 1,
				'showInteraction': false
			};
			twitterFetcher.fetch(tweetsConfig);
		}

		/*=================================
		=            Instagram            =
		=================================*/
		var instaEl = document.getElementById('instafeed');
		if (instaEl) {
			var feed = {};
			if (instaEl.getAttribute('data-user-id')) {
				feed = new Instafeed({
					get: 'user',
					userId: parseInt(instaEl.getAttribute('data-user-id')),
					accessToken: instaEl.getAttribute('data-access-token'),
					limit: 9
				});
			} else {
				feed = new Instafeed({
					get: 'tagged',
					tagName: instaEl.getAttribute('data-hashtag'),
					clientId: instaEl.getAttribute('data-client-id'),
					limit: 9
				});
			}
			feed.run();
		}



		/*============================================================
		=            Section layout fix for IE9 and lower            =
		============================================================*/
		function setSectionsBorderWidth() {
			var pageWidth = $('body').innerWidth();
			$('section[class*="section-bg"]').each(function() {
				if ($(this).hasClass('section-top-rise') || $(this).hasClass('section-top-fall')) {
					$(this).append('<div class="before" style="border-left-width:' + pageWidth + 'px" />');
				}
				if ($(this).hasClass('section-bottom-rise') || $(this).hasClass('section-bottom-fall')) {
					$(this).append('<div class="after" style="border-right-width:' + pageWidth + 'px" />');
				}
			});
		}
		function updateSectionsBorderWidth() {
			var newPageWidth = $('body').innerWidth();
			$('section[class*="section-bg"]').each(function() {
				if ($(this).hasClass('section-top-rise') || $(this).hasClass('section-top-fall')) {
					$('.before', this).css('border-left-width', newPageWidth);
				}
				if ($(this).hasClass('section-bottom-rise') || $(this).hasClass('section-bottom-fall')) {
					$('.after', this).css('border-right-width', newPageWidth);
				}
			});
		}
		if ($('html').hasClass('lte-ie9')) {
			setSectionsBorderWidth();
			$(window).on('resize', function() {
				updateSectionsBorderWidth();
			});
		}

	});

	(function() {
		var lastTime = 0;
		var vendors = ['webkit', 'moz'];
		for(var x = 0; x < vendors.length && !window.requestAnimationFrame; ++x) {
			window.requestAnimationFrame = window[vendors[x] + 'RequestAnimationFrame'];
			window.cancelAnimationFrame =
			window[vendors[x] + 'CancelAnimationFrame'] || window[vendors[x] + 'CancelRequestAnimationFrame'];
		}

		if (!window.requestAnimationFrame) {
			window.requestAnimationFrame = function(callback, element) {
				var currTime = new Date().getTime();
				var timeToCall = Math.max(0, 16 - (currTime - lastTime));
				var id = window.setTimeout(function() { callback(currTime + timeToCall); },
					timeToCall);
				lastTime = currTime + timeToCall;
				return id;
			};

			if (!window.cancelAnimationFrame) {
				window.cancelAnimationFrame = function(id) {
					clearTimeout(id);
				};
			}
		}

	}());

}(jQuery));
